comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%

ignore:
  - "setup.py"
  - "langworld_db_data"
  - "langworld_db_pyramid/alembic"
  - "langworld_db_pyramid/pshell.py"
  - "langworld_db_pyramid/routes.py"
