from pathlib import Path

DIR_WITH_TEST_FILES = Path(__file__).parent / "test_data"

DIR_WITH_INITIALIZE_DB_TEST_FILES = DIR_WITH_TEST_FILES / "initialize_db"
DIR_WITH_FEATURE_PROFILES_FOR_INITIALIZE_DB = (
    DIR_WITH_INITIALIZE_DB_TEST_FILES / "feature_profiles"
)
FILE_WITH_COUNTRIES_FOR_INITIALIZE_DB = DIR_WITH_INITIALIZE_DB_TEST_FILES / "countries.csv"
FILE_WITH_DOCULECTS_FOR_INITIALIZE_DB = DIR_WITH_INITIALIZE_DB_TEST_FILES / "doculects.csv"
FILE_WITH_CATEGORIES_FOR_INITIALIZE_DB = (
    DIR_WITH_INITIALIZE_DB_TEST_FILES / "feature_categories.csv"
)
FILE_WITH_VALUE_TYPES_FOR_INITIALIZE_DB = (
    DIR_WITH_INITIALIZE_DB_TEST_FILES / "feature_value_types.csv"
)
FILE_WITH_FEATURES_FOR_INITIALIZE_DB = DIR_WITH_INITIALIZE_DB_TEST_FILES / "features.csv"
FILE_WITH_LISTED_VALUES_FOR_INITIALIZE_DB = (
    DIR_WITH_INITIALIZE_DB_TEST_FILES / "features_listed_values.csv"
)
FILE_WITH_MAPS_FOR_INITIALIZE_DB = DIR_WITH_INITIALIZE_DB_TEST_FILES / "encyclopedia_maps.csv"
FILE_WITH_MAP_TO_DOCULECT_FOR_INITIALIZE_DB = (
    DIR_WITH_INITIALIZE_DB_TEST_FILES / "encyclopedia_map_to_doculect.csv"
)
FILE_WITH_ENCYCLOPEDIA_VOLUMES_FOR_INITIALIZE_DB = (
    DIR_WITH_INITIALIZE_DB_TEST_FILES / "encyclopedia_volumes.csv"
)
FILE_WITH_GENEALOGY_HIERARCHY_FOR_INITIALIZE_DB = (
    DIR_WITH_INITIALIZE_DB_TEST_FILES / "genealogy_families_hierarchy.yaml"
)
FILE_WITH_GENEALOGY_NAMES_FOR_INITIALIZE_DB = (
    DIR_WITH_INITIALIZE_DB_TEST_FILES / "genealogy_families_names.csv"
)
