"""rename table for class DoculectFeatureValueComment

Revision ID: 66ae23254e01
Revises: 153536212bfb
Create Date: 2022-06-21 17:14:34.486344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ae23254e01'
down_revision = '153536212bfb'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments_for_feature_values_in_doculects',
    sa.Column('doculect_id', sa.Integer(), nullable=False),
    sa.Column('feature_value_id', sa.Integer(), nullable=False),
    sa.Column('text_en', sa.Text(), nullable=True),
    sa.Column('text_ru', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['doculect_id'], ['doculects.id'], name=op.f('fk_comments_for_feature_values_in_doculects_doculect_id_doculects')),
    sa.ForeignKeyConstraint(['feature_value_id'], ['feature_values.id'], name=op.f('fk_comments_for_feature_values_in_doculects_feature_value_id_feature_values')),
    sa.PrimaryKeyConstraint('doculect_id', 'feature_value_id', name=op.f('pk_comments_for_feature_values_in_doculects'))
    )
    op.drop_table('doculect_feature_value_comment')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doculect_feature_value_comment',
    sa.Column('doculect_id', sa.INTEGER(), nullable=False),
    sa.Column('feature_value_id', sa.INTEGER(), nullable=False),
    sa.Column('text_en', sa.TEXT(), nullable=True),
    sa.Column('text_ru', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['doculect_id'], ['doculects.id'], name='fk_doculect_feature_value_comment_doculect_id_doculects'),
    sa.ForeignKeyConstraint(['feature_value_id'], ['feature_values.id'], name='fk_doculect_feature_value_comment_feature_value_id_feature_values'),
    sa.PrimaryKeyConstraint('doculect_id', 'feature_value_id', name='pk_doculect_feature_value_comment')
    )
    op.drop_table('comments_for_feature_values_in_doculects')
    # ### end Alembic commands ###
