"""Add EncyclopediaMap and many-to-many relationship with Doculect

Revision ID: bc7c98b048ca
Revises: c7d2a90411b3
Create Date: 2022-08-21 18:25:18.351452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc7c98b048ca'
down_revision = 'c7d2a90411b3'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encyclopedia_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('en', sa.String(length=255), nullable=True),
    sa.Column('ru', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_encyclopedia_maps'))
    )
    op.create_table('encyclopedia_map_to_doculect',
    sa.Column('encyclopedia_map_id', sa.Integer(), nullable=False),
    sa.Column('doculect_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doculect_id'], ['doculects.id'], name=op.f('fk_encyclopedia_map_to_doculect_doculect_id_doculects')),
    sa.ForeignKeyConstraint(['encyclopedia_map_id'], ['encyclopedia_maps.id'], name=op.f('fk_encyclopedia_map_to_doculect_encyclopedia_map_id_encyclopedia_maps')),
    sa.PrimaryKeyConstraint('encyclopedia_map_id', 'doculect_id', name=op.f('pk_encyclopedia_map_to_doculect'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('encyclopedia_map_to_doculect')
    op.drop_table('encyclopedia_maps')
    # ### end Alembic commands ###
