"""change associationtable to ORM

Revision ID: dc033efc3629
Revises: 46dccbb71c31
Create Date: 2022-06-20 22:08:45.472306

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'dc033efc3629'
down_revision = '46dccbb71c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
