"""rename relationship in Doculect

Revision ID: 6ecd3a72f0a7
Revises: c0f17d34f98e
Create Date: 2022-09-20 18:24:49.613784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ecd3a72f0a7'
down_revision = 'c0f17d34f98e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
