"""create relationship between Doculect and Family

Revision ID: bef39c85c32b
Revises: ed883bd4fd92
Create Date: 2022-07-08 18:30:32.389357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef39c85c32b'
down_revision = 'ed883bd4fd92'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doculects', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_doculects_family_id_families'), 'families', ['family_id'], ['id'])

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doculects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_doculects_family_id_families'), type_='foreignkey')

    # ### end Alembic commands ###
