"""start over

Revision ID: 037133a36ab7
Revises: 
Create Date: 2022-06-20 18:52:32.824026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037133a36ab7'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('man_id', sa.String(length=3), nullable=True),
    sa.Column('iso', sa.String(length=3), nullable=True),
    sa.Column('is_historical', sa.Boolean(), nullable=True),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('name_ru', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_countries'))
    )
    op.create_table('doculect_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=50), nullable=True),
    sa.Column('name_ru', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doculect_types'))
    )
    op.create_table('encyclopedia_volumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('en', sa.String(length=255), nullable=True),
    sa.Column('ru', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('pagenum_offset', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_encyclopedia_volumes'))
    )
    op.create_table('feature_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('man_id', sa.String(length=2), nullable=True),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('name_ru', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_categories'))
    )
    op.create_table('feature_value_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_value_types'))
    )
    op.create_table('doculects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('man_id', sa.String(length=100), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('is_extinct', sa.Boolean(), nullable=True),
    sa.Column('is_multiple', sa.Boolean(), nullable=True),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('name_ru', sa.String(length=255), nullable=True),
    sa.Column('custom_title_en', sa.String(length=255), nullable=True),
    sa.Column('custom_title_ru', sa.String(length=255), nullable=True),
    sa.Column('aliases_en', sa.String(), nullable=True),
    sa.Column('aliases_ru', sa.String(), nullable=True),
    sa.Column('family_id', sa.String(length=50), nullable=True),
    sa.Column('iso_639_3', sa.String(), nullable=True),
    sa.Column('glottocode', sa.String(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('main_country_id', sa.Integer(), nullable=True),
    sa.Column('encyclopedia_volume_id', sa.Integer(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('has_feature_profile', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['encyclopedia_volume_id'], ['encyclopedia_volumes.id'], name=op.f('fk_doculects_encyclopedia_volume_id_encyclopedia_volumes')),
    sa.ForeignKeyConstraint(['main_country_id'], ['countries.id'], name=op.f('fk_doculects_main_country_id_countries')),
    sa.ForeignKeyConstraint(['type_id'], ['doculect_types.id'], name=op.f('fk_doculects_type_id_doculect_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doculects'))
    )
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('man_id', sa.String(length=10), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('name_ru', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['feature_categories.id'], name=op.f('fk_features_category_id_feature_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_features'))
    )
    op.create_table('feature_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('man_id', sa.String(length=20), nullable=True),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('name_ru', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], name=op.f('fk_feature_values_feature_id_features')),
    sa.ForeignKeyConstraint(['type_id'], ['feature_value_types.id'], name=op.f('fk_feature_values_type_id_feature_value_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_values')),
    sa.UniqueConstraint('feature_id', 'type_id', 'name_en', 'name_ru', name=op.f('uq_feature_values_feature_id'))
    )
    op.create_table('doculect_to_feature_value',
    sa.Column('doculect_id', sa.Integer(), nullable=False),
    sa.Column('feature_value_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doculect_id'], ['doculects.id'], name=op.f('fk_doculect_to_feature_value_doculect_id_doculects')),
    sa.ForeignKeyConstraint(['feature_value_id'], ['feature_values.id'], name=op.f('fk_doculect_to_feature_value_feature_value_id_feature_values')),
    sa.PrimaryKeyConstraint('doculect_id', 'feature_value_id', name=op.f('pk_doculect_to_feature_value'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doculect_to_feature_value')
    op.drop_table('feature_values')
    op.drop_table('features')
    op.drop_table('doculects')
    op.drop_table('feature_value_types')
    op.drop_table('feature_categories')
    op.drop_table('encyclopedia_volumes')
    op.drop_table('doculect_types')
    op.drop_table('countries')
    # ### end Alembic commands ###
