"""change types of columns for latitude and longitude from Numeric to String

Revision ID: b65301860518
Revises: d43be6e8f09e
Create Date: 2022-06-22 13:03:09.608462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b65301860518'
down_revision = 'd43be6e8f09e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
