"""create separate tables for glottocodes and ISO-639-3 codes, create relationships with Doculect

Revision ID: 98874f7b044e
Revises: 246890497aa1
Create Date: 2022-06-23 16:53:03.623150

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '98874f7b044e'
down_revision = '246890497aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glottocodes', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('code', sa.String(length=10), nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_glottocodes')))
    op.create_table('iso_639p3_codes', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('code', sa.String(length=3), nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_iso_639p3_codes')))
    op.create_table(
        'doculect_to_glottocode', sa.Column('doculect_id', sa.Integer(), nullable=False),
        sa.Column('glottocode_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['doculect_id'], ['doculects.id'],
                                name=op.f('fk_doculect_to_glottocode_doculect_id_doculects')),
        sa.ForeignKeyConstraint(['glottocode_id'], ['glottocodes.id'],
                                name=op.f('fk_doculect_to_glottocode_glottocode_id_glottocodes')),
        sa.PrimaryKeyConstraint('doculect_id', 'glottocode_id', name=op.f('pk_doculect_to_glottocode')))
    op.create_table(
        'doculect_to_iso_639p3_code', sa.Column('doculect_id', sa.Integer(), nullable=False),
        sa.Column('iso_639p3_code_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['doculect_id'], ['doculects.id'],
                                name=op.f('fk_doculect_to_iso_639p3_code_doculect_id_doculects')),
        sa.ForeignKeyConstraint(['iso_639p3_code_id'], ['iso_639p3_codes.id'],
                                name=op.f('fk_doculect_to_iso_639p3_code_iso_639p3_code_id_iso_639p3_codes')),
        sa.PrimaryKeyConstraint('doculect_id', 'iso_639p3_code_id', name=op.f('pk_doculect_to_iso_639p3_code')))
    with op.batch_alter_table('doculects', schema=None) as batch_op:
        batch_op.drop_column('iso_639_3')
        batch_op.drop_column('glottocode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doculects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('glottocode', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('iso_639_3', sa.VARCHAR(), nullable=True))

    op.drop_table('doculect_to_iso_639p3_code')
    op.drop_table('doculect_to_glottocode')
    op.drop_table('iso_639p3_codes')
    op.drop_table('glottocodes')
    # ### end Alembic commands ###
