"""add comment columns to association table

Revision ID: 46dccbb71c31
Revises: 7c95a38b9123
Create Date: 2022-06-20 19:18:00.606497

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '46dccbb71c31'
down_revision = '7c95a38b9123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
