"""rename DoculectFeatureValueComment -> ...Info, add page_numbers

Revision ID: c0f17d34f98e
Revises: 31f7393c69c5
Create Date: 2022-09-20 18:15:38.669052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f17d34f98e'
down_revision = '31f7393c69c5'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additional_info_for_feature_values_in_doculects',
    sa.Column('doculect_id', sa.Integer(), nullable=False),
    sa.Column('feature_value_id', sa.Integer(), nullable=False),
    sa.Column('page_numbers', sa.String(length=20), nullable=True),
    sa.Column('text_en', sa.Text(), nullable=True),
    sa.Column('text_ru', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['doculect_id'], ['doculects.id'], name=op.f('fk_additional_info_for_feature_values_in_doculects_doculect_id_doculects')),
    sa.ForeignKeyConstraint(['feature_value_id'], ['feature_values.id'], name=op.f('fk_additional_info_for_feature_values_in_doculects_feature_value_id_feature_values')),
    sa.PrimaryKeyConstraint('doculect_id', 'feature_value_id', name=op.f('pk_additional_info_for_feature_values_in_doculects'))
    )
    op.drop_table('comments_for_feature_values_in_doculects')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments_for_feature_values_in_doculects',
    sa.Column('doculect_id', sa.INTEGER(), nullable=False),
    sa.Column('feature_value_id', sa.INTEGER(), nullable=False),
    sa.Column('text_en', sa.TEXT(), nullable=True),
    sa.Column('text_ru', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['doculect_id'], ['doculects.id'], name='fk_comments_for_feature_values_in_doculects_doculect_id_doculects'),
    sa.ForeignKeyConstraint(['feature_value_id'], ['feature_values.id'], name='fk_comments_for_feature_values_in_doculects_feature_value_id_feature_values'),
    sa.PrimaryKeyConstraint('doculect_id', 'feature_value_id', name='pk_comments_for_feature_values_in_doculects')
    )
    op.drop_table('additional_info_for_feature_values_in_doculects')
    # ### end Alembic commands ###
