"""rename backref for elements

Revision ID: 6daa4c3fcc94
Revises: f98db9ff84bb
Create Date: 2023-04-26 13:24:09.411077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6daa4c3fcc94'
down_revision = 'f98db9ff84bb'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
