"""remove element_id

Revision ID: 9df33f0e3069
Revises: 65075d343538
Create Date: 2023-04-26 13:33:39.934068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df33f0e3069'
down_revision = '65075d343538'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature_values', schema=None) as batch_op:
        batch_op.drop_constraint('fk_feature_values_element_id_feature_values', type_='foreignkey')
        batch_op.drop_column('element_id')

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature_values', schema=None) as batch_op:
        batch_op.add_column(sa.Column('element_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_feature_values_element_id_feature_values', 'feature_values', ['element_id'], ['id'])

    # ### end Alembic commands ###
