"""add children to FeatureValue

Revision ID: 5c12c8e2a74b
Revises: 6ecd3a72f0a7
Create Date: 2023-04-24 17:12:11.981807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c12c8e2a74b'
down_revision = '6ecd3a72f0a7'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature_values', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_feature_values_parent_id_feature_values'), 'feature_values', ['parent_id'], ['id'])

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature_values', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_feature_values_parent_id_feature_values'), type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
