"""revert: remove compound_id

Revision ID: 65075d343538
Revises: 6daa4c3fcc94
Create Date: 2023-04-26 13:27:14.133984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65075d343538'
down_revision = '6daa4c3fcc94'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature_value_compound_to_element', schema=None) as batch_op:
        batch_op.drop_constraint('fk_feature_value_compound_to_element_compound_id_feature_values', type_='foreignkey')
        batch_op.drop_constraint('fk_feature_value_compound_to_element_element_id_feature_values', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_feature_value_compound_to_element_compound_id_feature_values'), 'feature_values', ['compound_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_feature_value_compound_to_element_element_id_feature_values'), 'feature_values', ['element_id'], ['id'])

    with op.batch_alter_table('feature_values', schema=None) as batch_op:
        batch_op.drop_constraint('fk_feature_values_compound_id_feature_values', type_='foreignkey')
        batch_op.drop_column('compound_id')

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature_values', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compound_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_feature_values_compound_id_feature_values', 'feature_values', ['compound_id'], ['id'])

    with op.batch_alter_table('feature_value_compound_to_element', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_feature_value_compound_to_element_element_id_feature_values'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_feature_value_compound_to_element_compound_id_feature_values'), type_='foreignkey')
        batch_op.create_foreign_key('fk_feature_value_compound_to_element_element_id_feature_values', 'feature_values', ['element_id'], ['element_id'])
        batch_op.create_foreign_key('fk_feature_value_compound_to_element_compound_id_feature_values', 'feature_values', ['compound_id'], ['compound_id'])

    # ### end Alembic commands ###
