"""rename class

Revision ID: 7855e7bce02a
Revises: 710efc914057
Create Date: 2023-04-26 13:06:17.498829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7855e7bce02a'
down_revision = '710efc914057'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
