"""add descriptions to features

Revision ID: 8bbc29e60d27
Revises: 9ba6a43ceebf
Create Date: 2024-02-08 20:08:09.934036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bbc29e60d27'
down_revision = '9ba6a43ceebf'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doculects', schema=None) as batch_op:
        batch_op.alter_column('family_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_html_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description_html_ru', sa.Text(), nullable=True))

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.drop_column('description_html_ru')
        batch_op.drop_column('description_html_en')

    with op.batch_alter_table('doculects', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('family_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
