"""add PHOIBLE code

Revision ID: 33d5c6353a86
Revises: 986ff9182c29
Create Date: 2025-07-28 17:52:41.112146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33d5c6353a86'
down_revision = '986ff9182c29'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phoible_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phoible_codes'))
    )
    with op.batch_alter_table('phoible_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phoible_codes_code'), ['code'], unique=False)

    op.create_table('doculect_to_phoible_code',
    sa.Column('doculect_id', sa.Integer(), nullable=False),
    sa.Column('phoible_code_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doculect_id'], ['doculects.id'], name=op.f('fk_doculect_to_phoible_code_doculect_id_doculects')),
    sa.ForeignKeyConstraint(['phoible_code_id'], ['phoible_codes.id'], name=op.f('fk_doculect_to_phoible_code_phoible_code_id_phoible_codes')),
    sa.PrimaryKeyConstraint('doculect_id', 'phoible_code_id', name=op.f('pk_doculect_to_phoible_code'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doculect_to_phoible_code')
    with op.batch_alter_table('phoible_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phoible_codes_code'))

    op.drop_table('phoible_codes')
    # ### end Alembic commands ###
