"""add_wals_code_table_and_relationship

Revision ID: d58224d50b4c
Revises: 4ff3ab8b300e
Create Date: 2025-05-27 15:58:18.117014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd58224d50b4c'
down_revision = '4ff3ab8b300e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wals_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wals_codes'))
    )
    with op.batch_alter_table('wals_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wals_codes_code'), ['code'], unique=False)

    op.create_table('doculect_to_wals_code',
    sa.Column('doculect_id', sa.Integer(), nullable=False),
    sa.Column('wals_code_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doculect_id'], ['doculects.id'], name=op.f('fk_doculect_to_wals_code_doculect_id_doculects')),
    sa.ForeignKeyConstraint(['wals_code_id'], ['wals_codes.id'], name=op.f('fk_doculect_to_wals_code_wals_code_id_wals_codes')),
    sa.PrimaryKeyConstraint('doculect_id', 'wals_code_id', name=op.f('pk_doculect_to_wals_code'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doculect_to_wals_code')
    with op.batch_alter_table('wals_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wals_codes_code'))

    op.drop_table('wals_codes')
    # ### end Alembic commands ###
