"""add Grambank code

Revision ID: 986ff9182c29
Revises: d58224d50b4c
Create Date: 2025-07-28 17:30:22.048979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986ff9182c29'
down_revision = 'd58224d50b4c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grambank_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grambank_codes'))
    )
    with op.batch_alter_table('grambank_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grambank_codes_code'), ['code'], unique=False)

    op.create_table('doculect_to_grambank_code',
    sa.Column('doculect_id', sa.Integer(), nullable=False),
    sa.Column('grambank_code_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doculect_id'], ['doculects.id'], name=op.f('fk_doculect_to_grambank_code_doculect_id_doculects')),
    sa.ForeignKeyConstraint(['grambank_code_id'], ['grambank_codes.id'], name=op.f('fk_doculect_to_grambank_code_grambank_code_id_grambank_codes')),
    sa.PrimaryKeyConstraint('doculect_id', 'grambank_code_id', name=op.f('pk_doculect_to_grambank_code'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doculect_to_grambank_code')
    with op.batch_alter_table('grambank_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grambank_codes_code'))

    op.drop_table('grambank_codes')
    # ### end Alembic commands ###
