name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_LOGIN }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            set -e
            cd /home/${{ secrets.VPS_LOGIN }}/langworld_db_pyramid
            
            # BOOTSTRAP: Update the code to the latest version
            git fetch origin master
            git reset --hard origin/master
            
            # Make sure the script is executable
            # NOTE: this assumes the script was copied from server_side_sample.sh and modified accordingly
            chmod +x bash_scripts/server_side.sh
            
            # Execute the (now updated) script
            ./bash_scripts/server_side.sh
