name: main

on: [push]

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: install deps
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: copy settings
        run: |
          cp ./config/default/testing.ini ./config/testing.ini
      - name: compile Babel files
        run: |
          pybabel compile --directory=langworld_db_pyramid/locale --locale=en
      - name: run tests
        run: |
          pipenv run pytest -v --tb=short --cov=./ --cov-report=xml
      - name: Submit coverage
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
